### ISSUE TITLE
Consistent URLs to discord

### ISSUE THREAD

**Issue by lovincyrus** [cosmos/cosmos.network#116]
![image](https://user-images.githubusercontent.com/1021101/113792198-2e6fc780-96fa-11eb-8793-149d94046a3f.png)

Provide services - https://discord.gg/vcExX9T
Become a validator - https://discord.gg/g8vYRa9zQJ

**Comment by nassdonald** [comment]
This is intentional, since we need to direct validators to the validator-specific channel. The services link is trickier to define, so I believe this is just going to the default `read-first` channel.
