### ISSUE TITLE
Update Telegram link preview images

### ISSUE THREAD

**Issue by nassdonald** [cosmos/cosmos.network#119]
Currently when you share a link to the Cosmos website on Telegram, it seems to still display the old link preview image. [This SO answer](https://stackoverflow.com/a/35793374/1712562) may help us to figure out how to update it.

![image](https://user-images.githubusercontent.com/2961244/113946513-87c21e80-9800-11eb-96ce-0cce70f0246f.png)

**Comment by lovincyrus** [comment]
![image](https://user-images.githubusercontent.com/1021101/113947128-cd5df780-97be-11eb-856d-39b8eecf231b.png)
