### ISSUE TITLE
Invalid link to Atomic wallet

### ISSUE THREAD

**Issue by alain2sf** [cosmos/cosmos.network#120]
On page [](https://cosmos.network/ecosystem/wallets) in the iOS wallets group, the "Atomic Wallet" icon/link is not [](https://atomicwallet.io/) but [](https://www.atoken.com/ )(the one above for AToken wallet).

**Comment by lovincyrus** [comment]
![image](https://user-images.githubusercontent.com/1021101/114062133-042e1f00-984c-11eb-96d9-cee09d7722a5.png)

Just updated the Atomic wallet homepage.
