### ISSUE TITLE
proposal: show current testnet status on homepage

### ISSUE THREAD

**Issue by nylira** [cosmos/cosmos.network#122]
- [ ] create a simple blockchain monitor on the homepage that shows the current status of gaia-2 (or future testnets)

Reasoning: We need to show that our network is alive and breathing to site visitors, so they know this project is being worked on.

**Comment by jolesbi** [comment]
maybe a link that says "Testnet now live!" or something would be enough?

**Comment by nylira** [comment]
@jolesbi yeah that would be a great start. What should we link to though? It would be great to see some live ping statistics or the IPs of all the validators scattered across a map of earth...

**Comment by faboweb** [comment]
I think JB meant just a label stating "up" or "down". How much effort would it be to set the live ping list/map up?

**Comment by jolesbi** [comment]
yes, sorry. a label or notification, not necessarily a link.

**Comment by nylira** [comment]
Blocked on having a stable testnet.

**Comment by nylira** [comment]
Okay, testnets are here and they are mighty stable. `gaia-4000` is at 500k blocks. I've linked to network explorer in #169
