### ISSUE TITLE
Website doesn't work using Internet Explorer 11

### ISSUE THREAD

**Issue by mdyring** [cosmos/cosmos.network#124]
Page doesn't load, details in screenshot.

![image](https://user-images.githubusercontent.com/18033781/36539368-e187e86c-17d6-11e8-87b2-99901abce435.png)

**Comment by jolesbi** [comment]
uh oh

**Comment by faboweb** [comment]
IE11 doesn't have Promises. We need to add a polyfill or a message we don't supper IE11 ;-D

**Comment by nylira** [comment]
I'll get on this.

**Comment by nylira** [comment]
Okay, IE11 also doesn't support flexbox properly for the roadmap. Let's see...
