### ISSUE TITLE
unable to return to bookmarked page for cosmos.network FAQ page 

### ISSUE THREAD

**Issue by barriebyron** [cosmos/cosmos.network#150]
I like to refer back to specific FAQ items, but I don't seem to be able to successfully return to a bookmarked page.

For example, I visit this FAQ page often:  https://cosmos.network/learn/faq/what-problems-does-cosmos-solve 
so I bookmarked it using Google Chrome web browser, but then when I go to use that link
![image](https://user-images.githubusercontent.com/10067215/117039522-dfa45600-acd6-11eb-9764-d4121d4575c1.png)

I can successfully navigate to the page, but can't use a bookmark to return.  Teach me if there is a way!

**Comment by lovincyrus** [comment]
Thanks for reporting @barriebyron 😃 Pushing a fix right now.
