### ISSUE TITLE
Broken link on https://cosmos.network/intro

### ISSUE THREAD

**Issue by disinter** [cosmos/cosmos.network#158]
cosmost.network/intro links to "https://docs.tendermint.com/master/spec/consensus/fork-accountability.html" which gives a 404 error. The link is in the phrase "Security: Tendermint consensus is not only fault tolerant, it is also accountable. If the blockchain forks, there is a way to determine liability."

**Comment by lovincyrus** [comment]
Thanks for reporting @disinter ! I'll replace the URL asap.
