### ISSUE TITLE
Broken Links to Cosmos Hub & Docs Search 

### ISSUE THREAD

**Issue by RShip** [cosmos/cosmos.network#163]
Hello! Just wanted to give everyone a heads up. It looks like the links to hub.cosmos.network are broken. For example, the Validator Guide "Get Started" link on the community page (https://cosmos.network/community)

Goes to:
https://hub.cosmos.network/master/validators/overview.html
Should be:
https://hub.cosmos.network/main/validators/overview.html

Docs (https://docs.cosmos.network/):
Also, searching in the docs is broken. 

For example searching for store bring me to:
https://docs.cosmos.network/v0.40/core/store.html#store

Looks like it should be:
https://docs.cosmos.network/v0.41/core/store.html#store

Sorry I would submit a PR but I do not have the time to test! Thank you! :)

**Comment by lovincyrus** [comment]
Thanks for reporting @RShip

- I'll replace the hub.cosmos.network links in this repo. 🆗 
- searching `store` on http://docs.cosmos.network links me to https://docs.cosmos.network/v0.41/core/store.html#store. Can you still reproduce on your end?

**Comment by RShip** [comment]
Hey @lovincyrus, I am unable to replicate too. LGTM! Thank you! :)
