### ISSUE TITLE
Use new Cosmos Academy graphic.

### ISSUE THREAD

**Issue by nylira** [cosmos/cosmos.network#176]
![cosmos-academy](https://user-images.githubusercontent.com/172531/39804691-526ad6dc-53a7-11e8-8707-357f78e8f971.jpg)

**Comment by zramsay** [comment]
can't close issue

**Comment by nylira** [comment]
@zramsay This PR means to say that the `cosmos.network/academy` page needs this graphic. I'm working on adding it right now.
