### ISSUE TITLE
Expand ABCI explanation

### ISSUE THREAD

**Issue by rigelrozanski** [cosmos/cosmos.network#20]
From Emmanuel Odeke: 
Just a random nit I just noticed: introduces ABCI, but then states something without explaining why with the "thus it allows any...". Perhaps we could give a little background on why so?

https://github.com/cosmos/cosmos.github.io/blob/master/content/en-US/WHITEPAPER.md
```
Tendermint Core connects to blockchain applications via the Application 
Blockchain Interface (ABCI) [17]. Thus, ABCI allows for blockchain 
applications to be programmed in any language, not just the
programming language that the consensus engine is written in.
```

**Comment by jolesbi** [comment]
@chjango

**Comment by zramsay** [comment]
#142
