### ISSUE TITLE
Replace "$NaNB+" with loading state for homepage second section

### ISSUE THREAD

**Issue by nassdonald** [cosmos/cosmos.network#70]
![image](https://user-images.githubusercontent.com/2961244/113186409-88324680-924f-11eb-9c16-c702d8d1606c.png)

- [x] @miguel-tendermint to design a nice loading state for this value, while the backend request is being made.
- [x] @lovincyrus to implement loading state.
- [x] added 0 as default while it's calculating the total marketcap.
- [ ] ~~or use animated number https://codesandbox.io/s/v68x95mo30?file=/src/App.vue~~
- [x] or cache https://api.coingecko.com/api/v3/simple/price?ids=cosmos,iris-network,terra-luna,terrausd,binancecoin,okb,crypto-com-chain,thorchain,fetch-ai,kucoin-shares,mirror-protocol,kava,band-protocol,oasis-network,akash-network,secret,anchor-protocol,injective-protocol,bluzelle,switcheo,certik,sentinel-group,hard-protocol,oraichain-token,foam-protocol,kira-network,e-money,likecoin,starname,sifchain,bitsong&vs_currencies=usd&include_market_cap=true&include_24hr_vol=true&include_24hr_change=true&include_last_updated_at=true

**Comment by miguel-tendermint** [comment]
@lovincyrus What do you think about having random 2 digit numbers animated until we have a final value?
It may be too overkill to implement, and if that's the case, i can figure something out, but this would be cool!
![loadingnumbers](https://user-images.githubusercontent.com/76948640/113280761-a4c89000-92dc-11eb-9646-27c2975e756a.gif)
