### ISSUE TITLE
Fix homepage Starport card dyson sphere SVG rendering

### ISSUE THREAD

**Issue by nassdonald** [cosmos/cosmos.network#71]
Currently this renders differently from how it should (in Figma):

![image](https://user-images.githubusercontent.com/2961244/113186931-28886b00-9250-11eb-89af-4dfb308098ec.png)

**Comment by miguel-tendermint** [comment]
Should be good to go, using the Dyson sphere component and renders fine (tested on chrome and safari)
<img width="419" alt="Screenshot 2021-04-01 at 11 07 29" src="https://user-images.githubusercontent.com/76948640/113278966-75188880-92da-11eb-9b75-57faddf8a4f0.png">
@lovincyrus if you could re-export and replace would be awesome!
