### ISSUE TITLE
Add a link to the features page from the homepage Cosmos Hub section

### ISSUE THREAD

**Issue by nassdonald** [cosmos/cosmos.network#73]
@gamarin2's feedback:

> On the Homepage, I think we should add a link to the features pages in the "The Heart of the Interchain" section. It feels a bit weird that you cannot click to learn more about the Cosmos Hub

- [x] @miguel-tendermint to design.
- [x] @lovincyrus to implement.

**Comment by miguel-tendermint** [comment]
@lovincyrus added to figma!
